version: '3.8'

services:
  frontend:
    build:
      context: .     
      dockerfile: Dockerfile
    ports:
      - "4000:4000"             
    environment:
      - NODE_ENV=production     
    # volumes:
    #   - ./:/app       